"use client";
import { Card, CardHeader, CardTitle } from "@/components/ui/card";
import { QueryState } from "@/components/shared/query-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { useAccount, useCustomer } from "@/hooks/use-portal-queries";

export function CustomerDetailClient({ id }: { id: string }) {
  const customer = useCustomer(id);
  const account = useAccount();
  return <QueryState isLoading={customer.isLoading || account.isLoading} error={customer.error ?? account.error} data={customer.data && account.data ? { customer: customer.data, account: account.data } : undefined} onRetry={() => { void customer.refetch(); void account.refetch(); }}>{({ customer: location, account: acct }) => { const address = acct.addresses.find((item) => item.id === location.addressId); const buyers = acct.users.filter((user) => location.buyerIds.includes(user.id)); return <div className="grid gap-6 lg:grid-cols-2"><Card><h1 className="text-3xl font-bold">{location.name}</h1><p className="mt-2 text-slate-600">Location code {location.code}</p><p className="mt-2 text-sm text-slate-600">{location.profile.phone} · {location.profile.email}</p><div className="mt-4 flex gap-2"><StatusBadge status={location.status} /><StatusBadge status={location.profile.publicationStatus} /></div></Card><Card><CardHeader><CardTitle>Assigned buyers</CardTitle></CardHeader><ul className="space-y-2">{buyers.map((buyer) => <li key={buyer.id} className="rounded-lg border border-slate-200 p-3"><p className="font-medium">{buyer.name}</p><p className="text-sm text-slate-600">{buyer.email}</p></li>)}</ul></Card><Card><CardHeader><CardTitle>Address</CardTitle></CardHeader>{address ? <address className="not-italic text-sm text-slate-700">{address.line1}<br />{address.line2 ? <>{address.line2}<br /></> : null}{address.city}, {address.region} {address.postalCode}<br />{address.country}</address> : <p>No address assigned.</p>}</Card><Card><CardHeader><CardTitle>Profile contacts</CardTitle></CardHeader><ul className="space-y-2">{location.profile.contacts.map((contact) => <li key={contact.id} className="rounded-lg border border-slate-200 p-3"><p className="font-medium">{contact.name}</p><p className="text-sm text-slate-600">{contact.role} · {contact.email} · {contact.phone}</p></li>)}</ul><dl className="mt-4 space-y-1 text-sm"><div className="flex justify-between"><dt>Order updates</dt><dd>{location.profile.communicationPreferences.orderUpdates ? "On" : "Off"}</dd></div><div className="flex justify-between"><dt>Invoice reminders</dt><dd>{location.profile.communicationPreferences.invoiceReminders ? "On" : "Off"}</dd></div><div className="flex justify-between"><dt>Product alerts</dt><dd>{location.profile.communicationPreferences.productAlerts ? "On" : "Off"}</dd></div></dl></Card></div>; }}</QueryState>;
}
